#!/usr/bin/env bash
# Bash script configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Create the HTML directory and index file
mkdir -p /etc/nginx/html
echo "Holberton School" > /etc/nginx/html/index.html

# Configure Nginx server block
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
