#!/usr/bin/env bash
# Bash script configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "This is Sharon from Holberton School :)" | sudo tee /var/www/html/index.html > /dev/null

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com\/SMushy14 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
